spring:
  application:
    name: JwtSecurityApp
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jwtDb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework: DEBUG
